// <auto-generated />
using System;
using LeagueApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LeagueApi.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("LeagueApi.Domain.Competition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Competitions");
                });

            modelBuilder.Entity("LeagueApi.Domain.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AwayCorners")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AwayGoals")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AwayId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AwayShotsOffTarget")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AwayShotsOnTarget")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AwayShotsTotal")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AwayYellowCards")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CompetitionId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HomeCorners")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HomeGoals")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HomeId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HomeShotsOffTarget")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HomeShotsOnTarget")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HomeShotsTotal")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HomeYellowCards")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("KickoffUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AwayId");

                    b.HasIndex("HomeId");

                    b.HasIndex("CompetitionId", "Year");

                    b.HasIndex("CompetitionId", "Year", "HomeId", "AwayId")
                        .IsUnique();

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("LeagueApi.Domain.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("LeagueApi.Domain.Match", b =>
                {
                    b.HasOne("LeagueApi.Domain.Team", "Away")
                        .WithMany()
                        .HasForeignKey("AwayId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LeagueApi.Domain.Competition", "Competition")
                        .WithMany()
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LeagueApi.Domain.Team", "Home")
                        .WithMany()
                        .HasForeignKey("HomeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Away");

                    b.Navigation("Competition");

                    b.Navigation("Home");
                });
#pragma warning restore 612, 618
        }
    }
}
